version: '2.1'
services:
  eric-site-playlist-api:
    build:
      context: ../../../go/src/playlist-generator
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ../../../go/src/playlist-generator:/go/src/playlist-generator